"""Where the IXP collectors find the ``missing-peering-links`` companion repo.

The IXP snapshot is not fetched from an archive the way RouteViews is. It is
generated by ``wrapper.py`` in the separate, private ``missing-peering-links``
repo, under that repo's own Python environment, writing
``merged-members-gen-<YYYYMMDD>.txt`` into the repo's ``scripts/data``.

Those three paths used to be hardcoded to one laptop's layout
(``~/Documents/GitHub/missing-peering-links`` and
``~/miniforge3/envs/missing-peering-links/bin/python``), and both collectors
ignored the ``python_executable`` / ``output_dir`` constructor arguments they
advertised. Two consequences, both observed on ``hermes-ec2`` 2026-09-12:

* The IXP refresh cannot run anywhere the laptop layout is absent -- which is
  why IXP membership was last refreshed 2026-06-08 and has only ever been run by
  hand. Inside the pipeline container ``$HOME`` is ``/root``, so the paths do not
  resolve there either.
* Merely constructing a collector called ``os.makedirs(output_dir)`` and so
  created a phantom ``~/Documents/GitHub/missing-peering-links/scripts/data``
  tree on the VM -- 0 files, looking deceptively like a checkout that was never
  there. Directory creation now happens where files are actually written.

Resolution order for each path: explicit constructor argument, then environment
variable, then the historical default (so existing laptop runs are unchanged).
"""

import os

#: Default location of the companion repo, kept for backwards compatibility.
DEFAULT_IXP_REPO = os.path.join(
    os.path.expanduser("~"), "Documents", "GitHub", "missing-peering-links"
)

#: Default interpreter for the generator scripts, kept for backwards compatibility.
DEFAULT_IXP_PYTHON = os.path.join(
    os.path.expanduser("~"), "miniforge3", "envs", "missing-peering-links", "bin", "python"
)


def resolve_ixp_paths(
    python_executable: str | None = None,
    output_dir: str | None = None,
    wrapper_script_path: str | None = None,
) -> tuple[str, str, str]:
    """Resolve the wrapper script, interpreter, and snapshot output directory.

    Args:
        python_executable: Explicit interpreter for the generator scripts.
        output_dir: Explicit directory holding ``merged-members-gen-*.txt``.
        wrapper_script_path: Explicit path to ``wrapper.py``.

    Returns:
        ``(wrapper_script_path, python_executable, output_dir)``.

    Environment variables, used when the corresponding argument is None:
        ``HERMES_IXP_REPO``    -- repo root; the wrapper and output dir are
                                 derived from it as ``scripts/wrapper.py`` and
                                 ``scripts/data``.
        ``HERMES_IXP_WRAPPER`` -- wrapper script, overriding the derived path.
        ``HERMES_IXP_OUTPUT_DIR`` -- output dir, overriding the derived path.
        ``HERMES_IXP_PYTHON``  -- interpreter for the generator scripts.
    """
    repo = os.environ.get("HERMES_IXP_REPO", DEFAULT_IXP_REPO)

    wrapper = wrapper_script_path or os.environ.get(
        "HERMES_IXP_WRAPPER", os.path.join(repo, "scripts", "wrapper.py")
    )
    out_dir = output_dir or os.environ.get(
        "HERMES_IXP_OUTPUT_DIR", os.path.join(repo, "scripts", "data")
    )
    python_exe = python_executable or os.environ.get("HERMES_IXP_PYTHON", DEFAULT_IXP_PYTHON)

    return wrapper, python_exe, out_dir
